apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEB8aDNXHsynf2aMPsTGYvyLNASHt0lXxQXgnUYkbuVjg5QIqqaa/KqJHaGDM7XEEufszIRDq0q9JmsR9SbftELDuartyRddwqpc2A8czzcGpUgRuijI5BzpR/+997lzWv/lABQ3LQY+vdW6aRxdVDEIiBhWidSaCmWawKezqxvfAEF/uBm/XBXl/ZGTZqVAxAlnjn/d4QDqY3kaVI7kBO1UpuAIw9Gzg22KGh6fiIL65Qiud/Nxs69TdApyetnStrFmFnq7DgvyucdM5bX8OwPOtiwl/L2o+4tiDb8TXI+Yo7IXu9QUyLTvjSuYsSZ2yr+PnviPDP1Q7kvQYzF1nXu/lyXmuKUjCIqfkABeX7X7HKY4y/w==